language: node_js
node_js:
  - "14.17.0"
env:
  - NODE_ENV=TEST
cache:
  yarn: true
  directories:
    - "node_modules"
services:
  - docker
before_script:
  - yarn install
script:
  - yarn build || travis_terminate 1
  - export REPO=manuc66/node-hp-scan-to
  - docker build -f Dockerfile -t $REPO:latest .
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker push $REPO:latest
    fi
