language: node_js
node_js:
  - "14.17.0"
env:
  - NODE_ENV=TEST
cache:
  yarn: true
  directories:
    - "node_modules"
services:
  - docker
before_script:
  - yarn install
script:
  - yarn test-ci || travis_terminate 1
  - yarn build || travis_terminate 1
  - export REPO=manuc66/node-hp-scan-to
  - docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
after_success:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_PULL_REQUEST
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - if [ "$TRAVIS_REPO_SLUG" == "manuc66/node-hp-scan-to" -a "$TRAVIS_PULL_REQUEST" = "false"]; then docker tag $REPO:$TRAVIS_COMMIT $REPO:pr-${TRAVIS_PULL_REQUEST}; fi
  - if [ "$TRAVIS_REPO_SLUG" == "manuc66/node-hp-scan-to" -a "$TRAVIS_PULL_REQUEST" = "false"]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
  - if [ "$TRAVIS_REPO_SLUG" == "manuc66/node-hp-scan-to" -a "$TRAVIS_PULL_REQUEST" = "false"]; then docker push $REPO:$TAG; fi
